import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import ClientProvider from "./components/ClientProvider";
import store from "./context/store";
import { Provider } from "react-redux";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Provider store={store}>
          <ClientProvider>{children}</ClientProvider>
        </Provider>
      </body>
    </html>
  );
}
